{
 "title": "App Monitoring Groupe 3",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Evolution des requêtes par routes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "group by(handler) (http_requests_total{job=\"appli3\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_request_size_bytes_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "http_request_size_bytes_count", "legendFormat": "{{handler}}" }
   ]
  },
  {
   "title": "Moyenne en secondes du temps de latence sur le point predict",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{job=\"appli3\", handler=\"/predict\"}[5m]))\n/\nsum(rate(http_request_duration_seconds_count{job=\"appli3\", handler=\"/predict\"}[5m]))\n",
     "legendFormat": "Predict_point"
    }
   ]
  }
 ]
}