name: Python CI/CD - Full Pipeline & Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: '3.12'
        enable-cache: true

    - name: Install dependencies
      run: uv sync

    - name: Download raw data (Sources DVC)
      run: |
        mkdir -p data/models src/agentia/bdd
        
        curl -L "https://static.data.gouv.fr/resources/demandes-de-valeurs-foncieres/20251018-234902/valeursfoncieres-2025-s1.txt.zip" -o data/dvf.zip
        unzip -o data/dvf.zip -d data/
        mv data/valeursfoncieres-2025-s1.txt data/ValeursFoncieres-2025-S1.txt
        
        curl -L "https://www.data.gouv.fr/api/1/datasets/r/f5df602b-3800-44d7-b2df-fa40a0350325" -o data/communes-france-2025.csv

    - name: Reproduce DVC Pipeline
      run: |
        uv run dvc repro

    - name: Prepare SQLite Database
      run: |
        cd scripts
        uv run python transform_csv_to_db.py
        mkdir -p ../src/agentia/bdd/
        mv donnees_immo.db ../src/agentia/bdd/donnees_immo.db

    - name: Run tests with pytest
      run: uv run pytest tests/
